# Generated by Django 5.0 on 2024-01-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquiz',
            name='score',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
    ]
