# Generated by Django 4.2.7 on 2024-01-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_description_userquiz_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
