# Generated by Django 4.2.7 on 2024-01-24 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_like_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='quiz.quiz'),
        ),
    ]
