# Generated by Django 4.2.7 on 2024-01-24 16:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0008_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuiz',
            new_name='QuizResult',
        ),
    ]
