# Generated by Django 4.2.7 on 2024-01-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_choice_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
