# Generated by Django 5.0 on 2024-01-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
